import type { NextPage } from 'next'
import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Index from '../components/index'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Shimiiy / シミー</title>
        <meta name="description" content="Shimiiy's portfolio. Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          <Index />
        </h1>
      </main>
      
    </div>
  )
}

export default Home
